version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: build
          command: 'make build'
      - deploy:
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ];
                then ansible-playbook -i deploy/inventory deploy/deploy.yml;
              fi