version: 2
jobs:
  deploy:
    docker:
      - image: williamyeh/ansible:alpine3
    steps:
      - checkout
      - add_ssh_keys
      - run: ansible --version
      - deploy:
          command: cd deploy && ansible-playbook -e 'host_key_checking=False' -e 'deprecation_warnings=False' -i inventory deploy.yml
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
