version: 2
jobs:
  deploy:
    docker:
      - image: awilliamyeh/ansible:alpine3
    steps:
      - checkout
      - add_ssh_keys
      - run: ls -lha ~/.ssh
      - deploy:
          command: cd deploy && ansible-playbook -i inventory deploy.yml
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
