version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make build
      - run: cp bin/app deploy/roles/deploy/files/app
  deploy:
    docker:
      - image: williamyeh/ansible:alpine3-onbuild
    steps:
      - checkout
      - add_ssh_keys
      - deploy:
          command: ansible-playbook -i deploy/inventory deploy/deploy.yml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy