version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make build
      - run: cp bin/app deploy/roles/deploy/files/app
  deploy:
    docker:
      - image: williamyeh/ansible:alpine3-onbuild
    steps:
      - checkout
      - add_ssh_keys
      - run: echo '51.254.137.86 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaf/k/8ldUuXJ2kksFfEeNYwyMKbRmDKmkk/z1Mg6kW4sKvKg9uiE6goyOz/044bGRrzcp/slX4idlBIwm8XQQiddxT76iExrhPSpf8/qeZLKUgyipq62+GttXEhGZtLx8fc1OnXbVOP2jPup0bRqhh7Y3fAL3X2zpfW9KCRfCUqZta40RLrUGcYluODhNfGgWDDHY2ew5RXGoc8fZjlCY5yRhFd13GPYXHhlP36SjbhYR+BrsavEIOXZxnK3ZOxAMltFlcrPTErsNG5YnKYym6teOTPKH9t0qWsdETxE1t3OdtZQv48HPmoNMHdODzPeOHV8hAKC5pVRNvOD+j7qL' >> ~/.ssh/known_hosts
      - run: ls -lha ~/.ssh
      - run: cat ~/.ssh/id_rsa_06b1a65bde8c0f9f0f2c13a0ca4c72dc
      - deploy:
          command: ansible-playbook -i deploy/inventory deploy/deploy.yml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy