version: 2
jobs:
  deploy:
    docker:
      - image: ansible/centos7-ansible:stable
    steps:
      - checkout
      - add_ssh_keys
      - deploy:
          command: cd deploy && ansible-playbook -i inventory deploy.yml -vvv
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
