version: 2
jobs:
  deploy:
    docker:
      - image: williamyeh/ansible
    steps:
      - checkout
      - add_ssh_keys
      - run: ansible --version
      - deploy:
          command: cd deploy && ansible-playbook -i inventory deploy.yml
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
