version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/gebv/golang_with_deploy
    steps:
      - checkout
      - run: make build
      - persist_to_workspace:
          root: /go/src/github.com/gebv/golang_with_deploy
          paths:
            - bin/*
  deploy:
    docker:
      - image: williamyeh/ansible:alpine3
    working_directory: /go/src/github.com/gebv/golang_with_deploy
    steps:
      - checkout
      - add_ssh_keys
      - attach_workspace:
          at: /go/src/github.com/gebv/golang_with_deploy
      - run: ls -lha
      - run: cp ./bin/app ./deploy/roles/deploy/files/app
      - deploy:
          command: cd deploy && ansible-playbook -e 'host_key_checking=False' -e 'deprecation_warnings=False' -i inventory deploy.yml
  deploy_tag:
    docker:
      - image: williamyeh/ansible:alpine3
    working_directory: /go/src/github.com/gebv/golang_with_deploy
    steps:
      - run: echo "Deploy via TAG"
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  facke-deploy:
    jobs:
      build-and-deploy:
    jobs:
      - build
      - deploy_tag:
          requires:
            - build
          filters:
            tags:
              only: /stg.*/
            branches:
              ignore: /.*/
